### ISSUE TITLE
#149 not fixed

### ISSUE THREAD

**Issue by Pablete1234** [OvercastNetwork/SportBukkit#154]
i am using the same icarus design:
in vanilla 1.8.6 you get launched ~200 blocks
in sportbukkit 1.8 you get launched ~5 blocks

**Comment by twizmwazin** [comment]
Just ran a few tests on a vanilla 1.8.6 server with a vanilla 1.8.6 client, icaruses do appear to be much more effective than when using sportbukkit.

**Comment by twizmwazin** [comment]
@jedediah Just did some proper testing, ny_ and did some some tests with various builds.  
https://www.youtube.com/watch?v=nU6UH0ZMzrM

It appears to be a CraftBukkit issue rather than a SportBukkit issue, [here](https://hub.spigotmc.org/jira/browse/SPIGOT-949) is the CraftBukkit issue. I figure you should know, as Overcast's gameplay is most affected by this bug.

**Comment by mrapple** [comment]
Let's use the original issue please
