### ISSUE TITLE
Spawn Chunk Errors Out

### ISSUE THREAD

**Issue by AustinLMayes** [OvercastNetwork/SportBukkit#44]
Recently in the lobby the spawn chunk has unloaded itself. It is always that chunk and has happened more and more over the past week.

**Comment by LArrowHead** [comment]
Considering this is:
a: 3 Years old
b: Wasn't an issue
You should close it.

**Comment by twizmwazin** [comment]
@LArrowHead  While this may be old, you don't close issues simply because its been a while.

**Comment by LArrowHead** [comment]
Its an issue from an old lobby, that was a chunk error. Recently, there has
been no chunk error anymore on our lobbies. This is not an issue because
the lobby no longer exists and therefore the chunk error does not either.
There has been no reports of this ever occurring recently, so it is not a
valid issue anymore.
